// src/actions/types.js
export const FETCH_FOOTBALL_MATCHES_REQUEST = 'FETCH_FOOTBALL_MATCHES_REQUEST';
export const FETCH_FOOTBALL_MATCHES_SUCCESS = 'FETCH_FOOTBALL_MATCHES_SUCCESS';
export const FETCH_FOOTBALL_MATCHES_FAILURE = 'FETCH_FOOTBALL_MATCHES_FAILURE';
